### ISSUE TITLE
how to predict results in Attention_tf_data_generator_STT?

### ISSUE THREAD

**Issue by usamaehsan** [shenasa-ai/speech2text#1]
Aslam o Alaikum 
thanks for your great work 
can you please tell me how i can predict results in Attention_tf_data_generator_STT?

**Comment by masoudMZB** [comment]
Alaik-om-Aslam

If I undrestood well, you want to train with Attention model. and then predict one Sound.

For training you should first calculate MFCC or Spectrogram for sounds. then feed it to Network ( As in notebook ) 

for predicting you should first calculate MFCC or Spectrogram for sound. then use `predictions = model.predict(your_sound_mfcc_or_spectrogram)`

If there is still any question please let me know to answer you.
thanks for reading this repository

**Comment by usamaehsan** [comment]
wa alaikum slam 
sorry for my dumb questions
i am new to this feild and your repositry is only repositry on github which is helpfull for learning ASR even for a beginer like me.
if i understood correctly 
model=model.load(saved checkpoint from training) 
right?

**Comment by usamaehsan** [comment]
@masoudMZB by the way if you will write code for predicting single sound in after training code in notebook it will be very helpfull for beginners and i will be very thankfull to you

**Comment by masoudMZB** [comment]
Asking questions is best way to upgrade your knowledge.

no to clear it more it is like this
`prediction = your_last_checkpoint.predict(new_voice_to_transcribe)`

If you want to see most of the codes available in github for ASR check our wiki page in this repo : 
https://github.com/shenasa-ai/speech2text/wiki/Audio-Prepossessing-and-Guide-for-this-Type-of-Projects

in this page I Wrote every thing I found for start in this field. good luck man

**Comment by masoudMZB** [comment]
@usamaehsan I  will add predicting code soon. Thanks for your suggestion.

**Comment by usamaehsan** [comment]
thanks bro you are very helpfull

**Comment by masoudMZB** [comment]
your welcome. If you had any other idea share it with us.

I will close this issue.
