### ISSUE TITLE
راهنمایی

### ISSUE THREAD

**Issue by vahidalvandi** [shenasa-ai/speech2text#3]
سلام وقت بخیر
من دنبال یک روش هستم که صوتی که کاربر ارسال میکنه به متن تبدیل بشه . البته به صورت لوکال و روی سیستم باشه نه از api لطفا در مورد میزان دقت و نحوه استفاده از سرویسی که ساختید راهنمایی فرمایید

**Comment by masoudMZB** [comment]
سلام وقت شما بخیر
ببینید در روشی که از deepspeech استفاده شده کاملا این امکان فراهم هست که شما بتونید مدل روی روی خود موبایل اجرا کنید. برای اطلاعات بیشتر این لینک را بررسی کنید : 
https://discourse.mozilla.org/t/offline-speech-recognition-on-mobile/23004
این لینک کامیونیتی فعال در این مدل دیپ اسپیچ رو نشون میده.

همچنین روش های متنوع تری هم هست مثل استفاده از api google در اپلیکیشن موبالیتون یا هرجای دیگه. مثل مستندات جمع آوری دیتا که در همین ریپو هست

ضمنا تمام دیتاست (شامل +1000 ساعت داده ) بعلاوه تمام چکپوینت ها و هایپرپارامتر ها تا عید قرار هست open source بشن

**Comment by masoudMZB** [comment]
because of no reply I will close this issue. try to re open if you have question
