### ISSUE TITLE
سوالی در مورد دیتاست ورژن ۲

### ISSUE THREAD

**Issue by hamjam** [shenasa-ai/speech2text#5]
سلام
متن [دیتاست ورژن ۲ ](https://github.com/shenasa-ai/speech2text#full-dataset-part-1-part-2-will-be-uploaded-soon---) از خروجی مدل ASRای که آموزش دادید گرفته شده؟
چون confidence level داره و گفته بودید که متن‌ها دقیق نیست پرسیدم
با تشکر

**Comment by masoudMZB** [comment]
سلام 
نه این خروجی ها از مدل صوت به متن خودمون نیست. و وجود confidence level رو برای این اضافه کردیم که اگر در کاری فقط دیتاهای دقت بسیار بالا میخواید راحت تر بتونید فیلتر کنید

**Comment by ahkarami** [comment]
Hi,
Can you please explain how the transcriptions of the files were produced and with what model? Have you used Google API?

**Comment by masoudMZB** [comment]
Hi @ahkarami 
Yes, we used Google API to transcribe audio files. As you may know Google API return multiple prediction for an audio, the prediction with best confidence level was chosen

**Comment by ahkarami** [comment]
Thank you very much for your complete explanation.
