### ISSUE TITLE
Corrupt CSV files

### ISSUE THREAD

**Issue by nshmyrev** [shenasa-ai/speech2text#6]
Hi

Thanks a lot for sharing the dataset. Two CSV files uploaded seems corrupt, no data inside:

Varzesh_BashgahKhabar_79.csv
Tehran_Sahne_79.csv

Could you upload proper versions please?

**Comment by masoudMZB** [comment]
Hi 

yes, you are right those files are corrupted. unfortunately, the proper version of these 2 files is not in my SSD Hard. I'll ask my colleagues and upload it if they have it.

**Comment by masoudMZB** [comment]
unfortunately, I couldn't find the proper file. But If you are interested to create those files again. try to feed .wav files to one ASR system and get transcription. Sorry for the corrupted files. I'll close this issue
