### ISSUE TITLE
راه اندازی در رزبری

### ISSUE THREAD

**Issue by AmirAmraei** [shenasa-ai/speech2text#7]
سلام
اول تشکر می کنم بابت کار ارزشمندی که انجام دادین
و راهنمایی می فرمایین روی رزبری 4 راه اندازی کنم

**Comment by masoudMZB** [comment]
سلام وقت بخیر
تو برنامه ریزی هایی که کردیم برای انتشار نسخه های آموزش داده شده. مدل آموزش داده شده با deep speech رو داریم. که به زودی منتشر میشه چکپوینت های با دقت خوبش( البته دقت های محصول تجاری نیست ولی میتونید با دیتاست که متن باز منتشر کردیم و روش های جمع آوری دیتاست که توضیح دادیم، دقت مدل رو به وضعیت مخصول تجتاری برسونید).
با استفاده از اون چکپوینت ها میتونید توی هر بستری منتشر کنید. برای rasperi pi :


- [Documentation of Mozilla to use pretained model for exporting models ](https://deepspeech.readthedocs.io/en/r0.9/USING.html#getting-the-pre-trained-model)
- [Deep speech Forume (Raspberry Pi discussions )](https://discourse.mozilla.org/search?q=Raspberry%20Pi)
- [Deep speech Doc](https://deepspeech.readthedocs.io/en/latest/)
- [Deep speech Github](https://github.com/mozilla/DeepSpeech)
- [Sample repo (I didn't test this repo. just searched) ](https://github.com/touchgadget/DeepSpeech)
